### ISSUE TITLE
delegate pods always created at scheduler cluster

### ISSUE THREAD

**Issue by magiclamp2** [admiraltyio/multicluster-scheduler#10]
Having issue with scheduling pods on any cluster. The delegate pods always get created at the scheduler cluster even with annotation set to the other cluster.

Setup: 2 clusters created on top of bare-metal with cilium running(No mesh cluster yet). **c1** is the scheduler. deploy pods on **c2** and get delegate pods on **c1**. Great! but it still delegates to **c1** with annotation explicitly set to **c2**. If I try the other way around: deploy pods on **c1** and it also delegates to **c1** even with the annotation set.

I want to fix this and at least able to get delegate pods on **c2** when I deploy on **c1**. any suggestions? Thanks!

kubernetes version: `1.6.0`
cilium version: `1.6.3`

deploy pods on **c2**
expected: yes
```
$ kubectl --context c2 get pods
NAME                      READY   STATUS    RESTARTS   AGE
nginx-69c855d8f5-hp54d    1/1     Running   0          10m
nginx-69c855d8f5-lb578    1/1     Running   0          10m
nginx-69c855d8f5-zb5d6    1/1     Running   0          10m
ubuntu-56978cc9cb-7ql2q   1/1     Running   0          19s

$ kubectl --context c1 get pods
NAME                                 READY   STATUS    RESTARTS   AGE
c2-default-nginx-69c855d8f5-hp54d    1/1     Running   0          10m
c2-default-nginx-69c855d8f5-lb578    1/1     Running   0          10m
c2-default-nginx-69c855d8f5-zb5d6    1/1     Running   0          10m
c2-default-ubuntu-56978cc9cb-7ql2q   1/1     Running   0          71s

```

deploy pods on **c2**
expected: no, the delegate pods `c1-default-nginx...` should be created at c2 
```
$ kubectl  --context c1 get pods --watch
NAME                                 READY   STATUS    RESTARTS   AGE
c1-default-nginx-956d89fb-5w4bb      1/1     Running   0          17s
c1-default-nginx-956d89fb-gsvv6      1/1     Running   0          17s
c1-default-nginx-956d89fb-wx7fh      1/1     Running   0          17s
c2-default-ubuntu-56978cc9cb-7ql2q   1/1     Running   1          46h
nginx-956d89fb-5w4bb                 1/1     Running   0          18s
nginx-956d89fb-gsvv6                 1/1     Running   0          18s
nginx-956d89fb-wx7fh                 1/1     Running   0          17s```

**Comment by adrienjt** [comment]
That should work. Would you please confirm that you annotated the source pod template like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        multicluster.admiralty.io/elect: ""
        multicluster.admiralty.io/clustername: c2
    spec:
      containers:
        - name: nginx
          image: nginx
...
```
FYI, this is the code that handles enforced placement: https://github.com/admiraltyio/multicluster-scheduler/blob/81ed500c7a48b440ae083ddccfc1bb9ddf0d34fd/pkg/controllers/schedule/schedule.go#L171-L173
