### ISSUE TITLE
The Proxy Pod Logs an Error

### ISSUE THREAD

**Issue by jtr109** [admiraltyio/multicluster-scheduler#62]
## Summary

I built clusters and configured them as [the document](https://github.com/admiraltyio/multicluster-scheduler) says. The proxy pods works as expected on syncing status. But the logs of the proxies are not. I am not sure if it is in line with expectations.

## How to Reproduction?

my environment variables show below:

```shell
export CLUSTER1=cluster1-admin@cluster1
export CLUSTER2=cluster2-admin@cluster2
export NAMESPACE=default
```

I applied a deployment to specify running the pod on my $CLUSTER2:

```yaml
# remote-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: say
spec:
  replicas: 1
  selector:
    matchLabels:
      app: say
  template:
    metadata:
      labels:
        app: say
      annotations:
        multicluster.admiralty.io/elect: ""
        multicluster.admiralty.io/clustername: cluster2-admin@cluster2
    spec:
      containers:
      - name: say
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["hello world"]
```

After it was finish running. I printed the logs of the pod in $CLUSTER2. It showed as expected.

```shell
$ kubectl --context $CLUSTER2 logs say-6895d46c5c-pllx4-84wrs
 _____________
< hello world >
 -------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/
```

But the logs of the pod in $CLUSTER1 is different:

```shell
$ kubectl --context $CLUSTER1 logs say-6895d46c5c-pllx4
Error from server: no preferred addresses found; known addresses: []
```
