### ISSUE TITLE
Proxy pod appears running even if delegate pod isn't running yet

### ISSUE THREAD

**Issue by adrienjt** [admiraltyio/multicluster-scheduler#7]
The proxy pod is rapidly scheduled by its local cluster's scheduler (the default one or the one defined in the spec). This is misleading to the user, because the delegate pod may take longer to start in its target cluster (or stay pending if it's unschedulable).

The pod admission webhook should replace the scheduler name in the proxy pod's spec, so the agent can act as its single-cluster scheduler and only bind it to a node when the corresponding delegate pod is bound to a node in the target cluster.

**Comment by danikam** [comment]
Hello, we're running into this issue because the proxy pods will fill up the worker nodes to the maximum number of pods per node (110), at which point the delegate pods become unschedulable on that node. Is there a possibility of implementing a fix, or hints on implementing a fix ourselves? Thanks!

**Comment by danikam** [comment]
Alternatively, is there a way to modify the setup so that the proxy pods run on master nodes rather than worker nodes?

**Comment by adrienjt** [comment]
Hi @danikam, the fix that I suggested above when I initially wrote up this issue would actually create new problem. The delegate pod could be scheduled, run to completion, while its proxy pod would remain unschedulable, which would break the feedback loop. So, for now, I'd like to let the proxy pods run before the delegate pods.

Your particular issue is that proxy pods and delegate pods compete for a starved resource. As you mentioned, scheduling proxy pods to a subset of nodes would unlock your system. This would be done by the mutating admission webhook: https://github.com/admiraltyio/multicluster-scheduler/blob/master/pkg/webhooks/proxypod/proxypod.go. At first, to test the idea, you could hack a hardcoded `nodeSelector` on the proxy pod . We could then add a configuration value, e.g., as an annotation on the source pod (e.g., `multicluster.admiralty.io/proxy-pod-node-selector`).

**Comment by danikam** [comment]
Hi @adrienjt, many thanks for your quick reply! I like the idea of hardcoding the NodeSelector as as quick test, in fact I've been trying to find a way to do that today. I'm wondering if you could please point me to where the NodeSelector would need to be added?

**Comment by adrienjt** [comment]
Go is a compiled language, so you can't just edit a file in a running container. You'd need to pull the repo to your machine and add this line at the end of the `Handle` function:
```go
proxyPod.Spec.NodeSelector = map[string]string{"node-role.kubernetes.io/master":""}
```
Then, you'd build an image of the pod admission controller and push it to a registry that you and your cluster can push/pull to/from:
```sh
# (inspired from build/build.sh)
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o "_out/cmd/pod-admission-controller/manager" "admiralty.io/multicluster-scheduler/cmd/pod-admission-controller"
cp build/Dockerfile _out/
docker build -t "$YOUR_IMG_REGISTRY/multicluster-scheduler-pod-admission-controller:$SOME_TAG" --build-arg target="cmd/pod-admission-controller" _out
```
Then you'd replace the deployed image:
```sh
kubectl edit deployment pod-admission-controller -n multicluster-scheduler-agent
... 
```

**Comment by danikam** [comment]
Thank you for these very clear instructions! Works perfectly :) Just working on adding a NoSchedule toleration for the master nodes.

**Comment by danikam** [comment]
Got the toleration working finally :) I've attached the updated proxypod.go with your suggested 'nodeSelector hack'.
[proxypod.txt](https://github.com/admiraltyio/multicluster-scheduler/files/3894685/proxypod.txt)

**Comment by adrienjt** [comment]
I'm glad it's working, and thank you. If you'd like this merged, it would have to be configurable. Understandably, not all users want their proxy pods to be scheduled to master nodes. I'm thinking of a general solution that would allow users to apply a custom [strategic merge patch](https://github.com/eBay/Kubernetes/blob/master/docs/devel/api-conventions.md#patch-operations) to source pods when they become proxy pods. The patch could be stored as an annotation on each source pod (e.g., multicluster.admiralty.io/proxy-pod-strategic-merge-patch`), or in a ConfigMap that would be mounted inside the webhook container, to be applied to all source pods. The former is likely easier to implement at first. Let me know if you'd like to own this feature and submit a pull request.

Applied to the example of the README, here's what the patch would look like as an annotation in your case:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        multicluster.admiralty.io/elect: ""
        multicluster.admiralty.io/proxy-pod-strategic-merge-patch: |
          spec:
            nodeSelector:
              node-role.kubernetes.io/master:""
            tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
        ports:
        - containerPort: 80
```
